Controllers/PlantationsController.cs
using Flowers.Models;
using Flowers.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Flowers.Controllers
{
    public class PlantationsController : Controller
    {
        private readonly IRepository<Plantation> _plantations;

        public PlantationsController(IRepository<Plantation> plantations) =>
            _plantations = plantations;

        [HttpGet] 
        public IActionResult All() =>
            View(_plantations.All());

        [HttpGet]
        public IActionResult Get(string id)
        {
            var plantation = _plantations.Get(Convert.ToInt32(id));

            return View(plantation);
        }

        [HttpGet]
        public IActionResult Add() =>
            View();

        [HttpPost]
        public IActionResult Add(Plantation model)
        {
            _plantations.Add(model);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Remove(string value)
        {
            var id = Convert.ToInt32(value);

            _plantations.Remove(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            var plantation = _plantations.Get(Convert.ToInt32(id));

            return View(plantation);
        }

        [HttpPost]
        public IActionResult Update(Plantation model)
        {
            _plantations.Update(model);

            return RedirectToAction(nameof(All));
        }

        //public IActionResult AddFlower()
        //{

        //}
    }
}

Controllers/WarehousesController.cs
using Flowers.Models;
using Flowers.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Flowers.Controllers
{
    public class WarehousesController : Controller
    {
        private readonly IRepository<Warehouse> _warehouses;

        public WarehousesController(IRepository<Warehouse> warehouses) =>
            _warehouses = warehouses;

        [HttpGet]
        public IActionResult All() =>
            View(_warehouses.All());

        [HttpGet]
        public IActionResult Get(string id)
        {
            var warehouse = _warehouses.Get(Convert.ToInt32(id));

            return View(warehouse);
        }

        [HttpGet]
        public IActionResult Add() =>
            View();
            
        [HttpPost]
        public IActionResult Add(Warehouse model)
        {
            _warehouses.Add(model);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Remove(string value)
        {
            var id = Convert.ToInt32(value);

            _warehouses.Remove(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            var warehouse = _warehouses.Get(Convert.ToInt32(id));

            return View(warehouse);
        }

        [HttpPost]
        public IActionResult Update(Warehouse model)
        {
            _warehouses.Update(model);

            return RedirectToAction(nameof(All));
        }



        //public IActionResult AddFlower()
        //{

        //}
    }
}

Views/Warehouses/Add.cshtml
@model Warehouse

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add warehouse</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="Warehouses" asp-action="Add">
            <div asp-validation-summary="ModelOnly"></div>

            <div>
                <label asp-for="Name"><strong>Name</strong></label><br />
                <input asp-for="Name" class="form-control" placeholder="Name" />
            </div>
            <div>
                <label asp-for="Address"><strong>Address</strong></label><br />
                <input asp-for="Address" class="form-control" placeholder="Address" />
            </div>

            <button class="btn btn-dark" type="submit">Add</button>

        </form>
    </div>
</body>
</html>

<a asp-controller="Warehouses" asp-action="All">Cancel</a>

Views/Warehouses/All.cshtml
@model IEnumerable<Warehouse>

<a asp-controller="Home" asp-action="Index">Home</a> |
<a asp-controller="Warehouses" asp-action="All">Warehouses</a> |
<a asp-controller="Warehouses" asp-action="Add">Add warehouse</a> 

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var warehouse in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => warehouse.Id)</td>
            <td>@Html.DisplayFor(modelItem => warehouse.Name)</td>
            <td>@Html.DisplayFor(modelItem => warehouse.Address)</td>
            <td>
                <a asp-controller="Warehouses" asp-action="Remove" asp-route-value="@warehouse.Id">Remove</a> |
                <a asp-controller="Warehouses" asp-action="Get" asp-route-id="@warehouse.Id">Details</a> 
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Warehouses/Get.cshtml
@model Warehouse

<a asp-controller="Home" asp-action="Index">Home</a> |
<a asp-controller="Warehouses" asp-action="All">Warehouses</a> |
<a asp-controller="Warehouses" asp-action="Add">Add warehouse</a>

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
            <td>Address</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
            <td>@Model.Address</td>
        </tr>
    </tbody>
</table>

<a asp-controller="Warehouses" asp-action="Update" asp-route-id="@Model.Id">Update</a> |
<a asp-controller="Warehouses" asp-action="AddFlower" asp-route-id="@Model.Id">Add flowers</a> |
<a asp-controller="Warehouses" asp-action="All">Back</a>

Views/Warehouses/Update.cshtml
@model Warehouse

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add warehouse</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="Warehouses" asp-action="Update">
            <div asp-validation-summary="ModelOnly"></div>

            <input type="hidden" name="Id" value="@Model.Id" />

            <div>
                <label asp-for="Name"><strong>Name</strong></label><br />
                <input asp-for="Name" class="form-control" placeholder="Name" />
            </div>
            <div>
                <label asp-for="Address"><strong>Address</strong></label><br />
                <input asp-for="Address" class="form-control" placeholder="Address" />
            </div>

            <button class="btn btn-dark" type="submit">Update</button>

        </form>
    </div>
</body>
</html>

<a asp-controller="Plantations" asp-action="All">Cancel</a>