Models/Flower.cs
namespace Flowers.Models
{
    public class Flower : IEntity
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Controllers/FlowersController.cs
using Flowers.Models;
using Flowers.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Flowers.Controllers
{
    public class FlowersController : Controller
    {
        private readonly IRepository<Flower> _flowers;

        public FlowersController(IRepository<Flower> flowers) =>
            _flowers = flowers;

        [HttpGet]
        public IActionResult All() =>
            View(_flowers.All());

        [HttpGet]
        public IActionResult Get(string id)
        {
            var flower = _flowers.Get(Convert.ToInt32(id));

            return View(flower);
        }

        [HttpGet]
        public IActionResult Add() =>
            View();

        [HttpPost]
        public IActionResult Add(Flower model)
        {
            _flowers.Add(model);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Remove(string value)
        {
            var id = Convert.ToInt32(value);

            _flowers.Remove(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            var flower = _flowers.Get(Convert.ToInt32(id));

            return View(flower);
        }

        [HttpPost]
        public IActionResult Update(Flower model)
        {
            _flowers.Update(model);

            return RedirectToAction(nameof(All));
        }
    }
}

Views/Flowers/Add.cshtml
@model Flower

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add flower</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="FLowers" asp-action="Add">
            <div asp-validation-summary="ModelOnly"></div>

            <div>
                <label asp-for="Name"><strong>Name</strong></label><br />
                <input asp-for="Name" class="form-control" placeholder="Name" />
            </div>

            <button class="btn btn-dark" type="submit">Add</button>

        </form>
    </div>
</body>
</html>

<a asp-controller="Flowers" asp-action="All">Cancel</a>

Views/Flowers/All.cshtml
@model IEnumerable<Flower>

<a asp-controller="Home" asp-action="Index">Home</a> |
<a asp-controller="Flowers" asp-action="All">Flowers</a>|
<a asp-controller="Flowers" asp-action="Add">Add flower</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var flower in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => flower.Id)</td>
            <td>@Html.DisplayFor(modelItem => flower.Name)</td>
            <td>
                <a asp-controller="Flowers" asp-action="Remove" asp-route-value="@flower.Id">Remove</a> |
                <a asp-controller="Flowers" asp-action="Get" asp-route-id="@flower.Id">Detail</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Flowers/Get.cshtml
@model Flower

<table class="table">
    <thead>
        <tr>
            <td>Id</td>
            <td>Name</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.Name</td>
        </tr>
    </tbody>
</table>

<a asp-controller="Flowers" asp-action="Update" asp-route-id="@Model.Id">Update</a> |
<a asp-controller="Flowers" asp-action="All">Back</a>

Views/Flowers/Update.cshtml
@model Flower

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update flower</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="FLowers" asp-action="Update">
            <div asp-validation-summary="ModelOnly"></div>

            <input type="hidden" name="Id" value="@Model.Id" />

            <div>
                <label asp-for="Name"><strong>Name</strong></label><br />
                <input asp-for="Name" class="form-control" placeholder="Name" />
            </div>

            <button class="btn btn-dark" type="submit">Update</button>
        </form>
    </div>
</body>
</html>

<a asp-controller="Flowers" asp-action="All">Cancel</a>