Models/Supply.cs
using System;

namespace Flowers.Models
{
    public class Supply : IEntity
    {
        public int Id { get; set; }
        public int PlantationId { get; set; }
        public int WarehouseId { get; set; }

        public DateTime ScheduledDate { get; set; }
        public DateTime ClosedDate { get; set; }

        public Status Status { get; set; }
    }
}

Controllers/SuppliesController.cs
using Flowers.Models;
using Flowers.Repositories;
using Flowers.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace Flowers.Controllers
{
    public class SuppliesController : Controller
    {
        private readonly IRepository<Supply> _supplies;
        private readonly IRepository<Plantation> _plantations;
        private readonly IRepository<Warehouse> _warehouses;

        public SuppliesController(
            IRepository<Supply> supplies, 
            IRepository<Warehouse> warehouses, 
            IRepository<Plantation> plantations
            )
        {
            _supplies = supplies;
            _warehouses = warehouses;
            _plantations = plantations;
        }

        [HttpGet]
        public IActionResult All() =>
            View(_supplies.All());

        [HttpGet]
        public IActionResult Get(string id)
        {
            var supply = _supplies.Get(Convert.ToInt32(id));

            return View(supply);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var supply = new AddSupplyViewModel
            {
                Plantations = Plantations(),
                Warehouses = Warehouses()
            };

            return View(supply);
        }

        [HttpPost]
        public IActionResult Add(AddSupplyViewModel vm)
        {
            var supply = new Supply
            {
                Id = vm.Id,
                PlantationId = vm.PlantationId,
                WarehouseId = vm.WarehouseId,
                ScheduledDate = vm.ScheduledDate,
                ClosedDate = vm.ClosedDate,
                Status = vm.Status
            };

            _supplies.Add(supply);

            return RedirectToAction(nameof(All));
        }

        public IActionResult Remove(string value)
        {
            var id = Convert.ToInt32(value);

            _supplies.Remove(id);

            return RedirectToAction(nameof(All));
        }

        [HttpGet]
        public IActionResult Update(string id)
        {
            var supply = new UpdateSupplyViewModel
            {
                Id = Convert.ToInt32(id),
                Plantations = Plantations(),
                Warehouses = Warehouses()
            };

            return View(supply);
        }

        [HttpPost]
        public IActionResult Update(UpdateSupplyViewModel vm)
        {
            var supply = new Supply
            {
                Id = vm.Id,
                PlantationId = vm.PlantationId,
                WarehouseId = vm.WarehouseId,
                ScheduledDate = vm.ScheduledDate,
                ClosedDate = vm.ClosedDate,
                Status = vm.Status
            };

            _supplies.Update(supply);

            return RedirectToAction(nameof(All));
        }

        private List<SelectListItem> Plantations()
        {
            var items = new List<SelectListItem>();

            foreach (var plantation in _plantations.All())
                items.Add(new SelectListItem { Text = plantation.Name, Value = plantation.Id.ToString() });

            return items;
        }

        private List<SelectListItem> Warehouses()
        {
            var items = new List<SelectListItem>();

            foreach (var warehouse in _warehouses.All())
                items.Add(new SelectListItem { Text = warehouse.Name, Value = warehouse.Id.ToString() });

            return items;
        }
    }
}

Views/Supplies/Add.cshtml
@model Flowers.ViewModels.AddSupplyViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add supply</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="Supplies" asp-action="Add">
            <div asp-validation-summary="ModelOnly"></div>

            <label asp-for="PlantationId"><strong>Plantation</strong></label><br />
            <div>
                @Html.DropDownListFor(m => m.PlantationId, Model.Plantations, "Select the plantation", new { @class = "form-control" })
            </div>

            <label asp-for="WarehouseId"><strong>Warehouse</strong></label><br />
            <div>
                @Html.DropDownListFor(m => m.WarehouseId, Model.Warehouses, "Select the warehouse", new { @class = "form-control" })
            </div>
            <div>
                <label asp-for="ScheduledDate"><strong>Scheduled Date</strong></label><br />
                <input asp-for="ScheduledDate" class="form-control" placeholder="ScheduledDate" />
            </div>

            <div>
                <label asp-for="ClosedDate"><strong>Closed Date</strong></label><br />
                <input asp-for="ClosedDate" class="form-control" placeholder="ClosedDate" />
            </div>

            <div>
                <label asp-for="Status"><strong>Status</strong></label><br />
                <input asp-for="Status" class="form-control" placeholder="Status" />
            </div>

            <button class="btn btn-dark" type="submit">Add</button>

        </form>
    </div>
</body>
</html>

<a asp-controller="Supplies" asp-action="All">Cancel</a>

Views/Supplies/All.cshtml
@model IEnumerable<Supply>

<a asp-controller="Home" asp-action="Index">Home</a> |
<a asp-controller="Supplies" asp-action="All">Supplies</a> |
<a asp-controller="Supplies" asp-action="Add">Add supply</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Plantation Id</th>
            <th>Warehouse Id</th>
            <th>Scheduled Date</th>
            <th>Closed Date</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var supply in Model)
        {
        <tr>
            <td>@Html.DisplayFor(modelItem => supply.Id)</td>
            <td>@Html.DisplayFor(modelItem => supply.PlantationId)</td>
            <td>@Html.DisplayFor(modelItem => supply.WarehouseId)</td>
            <td>@Html.DisplayFor(modelItem => supply.ScheduledDate)</td>
            <td>@Html.DisplayFor(modelItem => supply.ClosedDate)</td>
            <td>@Html.DisplayFor(modelItem => supply.Status)</td>
            <td>
                <a asp-controller="Supplies" asp-action="Remove" asp-route-value="@supply.Id">Remove</a> |
                <a asp-controller="Supplies" asp-action="Get" asp-route-id="@supply.Id">Details</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Supplies/Get.cshtml
@model Supply

<a asp-controller="Home" asp-action="Index">Home</a> |
<a asp-controller="Supplies" asp-action="All">Supplies</a> |
<a asp-controller="Supplies" asp-action="Add">Add supply</a>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Plantation Id</th>
            <th>Warehouse Id</th>
            <th>Schedule Date</th>
            <th>Closed Date</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Id</td>
            <td>@Model.PlantationId</td>
            <td>@Model.WarehouseId</td>
            <td>@Model.ScheduledDate</td>
            <td>@Model.ClosedDate</td>
            <td>@Model.Status</td>
        </tr>
    </tbody>
</table>

<a asp-controller="Supplies" asp-action="Update" asp-route-id="@Model.Id">Update</a> |
<a asp-controller="Supplies" asp-action="All">Cancel</a>

Views/Supplies/Update.cshtml
@model Flowers.ViewModels.UpdateSupplyViewModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update supply</title>
</head>
<body>
    <div class="container">
        <form method="post" asp-controller="Supplies" asp-action="Update">
            <div asp-validation-summary="ModelOnly"></div>

            <label asp-for="PlantationId"><strong>Plantation</strong></label><br />
            <div>
                @Html.DropDownListFor(m => m.PlantationId, Model.Plantations, "Select the plantation", new { @class = "form-control" })
            </div>

            <label asp-for="WarehouseId"><strong>Warehouse</strong></label><br />
            <div>
                @Html.DropDownListFor(m => m.WarehouseId, Model.Warehouses, "Select the warehouse", new { @class = "form-control" })
            </div>
            <div>
                <label asp-for="ScheduledDate"><strong>Scheduled Date</strong></label><br />
                <input asp-for="ScheduledDate" class="form-control" placeholder="ScheduledDate" />
            </div>

            <div>
                <label asp-for="ClosedDate"><strong>Closed Date</strong></label><br />
                <input asp-for="ClosedDate" class="form-control" placeholder="ClosedDate" />
            </div>

            <div>
                <label asp-for="Status"><strong>Status</strong></label><br />
                <input asp-for="Status" class="form-control" placeholder="Status" />
            </div>

            <button class="btn btn-dark" type="submit">Update</button>

        </form>
    </div>
</body>
</html>

<a asp-controller="Supplies" asp-action="All">Cancel</a>